### ISSUE TITLE
[Feature request] - Default sorting options

### ISSUE THREAD

**Issue by Iliansic** [lotusgate/otraku#11]
Could you please add option for separate default sorting orders for anime and manga lists?

Also currently there are currently only four out of seven available default sorting options without ability to choose whether it will be descending or ascending order. If possible could you at least add "Airing at" to defaults, as that option is basically the best one at the start of the season.

**Comment by lotusgate** [comment]
I agree that the default sorting options are very limited. However, that is mostly due to the site being that way too. When you go to settings -> lists on the site, you will find the same 4 options.
Not to say that I can't implement what you mentioned, but I'm unsure whether I want to break the parity with the site 🤔.
