### ISSUE TITLE
Blur disabling option.

### ISSUE THREAD

**Issue by exkpwn** [lotusgate/otraku#27]
The blur is not present behind the statusbar or nav bar

Kinda inconsistent
Would be cool if you gave a option to disable the blur.
![Screenshot_20220225-163701_Otraku~2](https://user-images.githubusercontent.com/44256630/155705166-db0155a7-7537-46ca-a6ec-cc216274d2e4.png)

**Comment by lotusgate** [comment]
It is present in the nav bar though. It blurs the content below it - at the bottom of your screenshot, there's an image on the left and you see it blurred, but there's only text on the right and the blur isn't very apparent. If you go to the explore tab, you will notice that the blur looks fine there.

For the status bar - I may end up adding blur there, we will see.
However, I probably won't add an option to disable the blur altogether. It doesn't seem too useful.

**Comment by Curstantine** [comment]
I have a feeling that they're talking about the background color under navbar guide/system navbar background.

![Screenshot_20220510-141747_Neko](https://user-images.githubusercontent.com/69104500/167589596-7328288f-c6da-4f7a-a6d0-b9816fff3519.png)
![Screenshot_20220510-141950](https://user-images.githubusercontent.com/69104500/167589608-b6965e60-50c2-4186-9b2b-f531b2f88f07.png)

**Comment by lotusgate** [comment]
Hmm, I don't know how easy it would be to implement the transparency there, but I can try it sometime.

**Comment by lotusgate** [comment]
coming back to this issue, i still don't plan to add an option to disable the blur. Otherwise, in the upcoming update, the transparent effect of the top app bar will permeate through the status bar (the only exceptions being the media and user pages). I won't change the bottom bar behavior though, at least not for now. On ios, it works as you want. But on android, i had some troubles with the implementation. I don't know if I will come back to this, so I will close the issue, sorry. If I decide to work around the problem on my own accord, I may do something, but there are no current plans for that.
I will close the issue (but feel free to comment).

**Comment by lotusgate** [comment]
nvm @Curstantine gave me a tip on how to enable the blur at the bottom too, so that will come too.
